import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val vvalidator: String = "0.5.1"

  const val annotation: String = "1.1.0"

  const val appcompat: String = "1.1.0"

  const val browser: String = "1.2.0-alpha07"

  const val cardview: String = "1.0.0"

  const val constraintlayout: String = "1.1.3"

  const val androidx_lifecycle: String = "2.1.0"

  const val multidex_instrumentation: String = "2.0.0"

  const val multidex: String = "2.0.1"

  const val paging_runtime: String = "2.1.0"

  const val recyclerview: String = "1.1.0-beta04"

  const val com_android_tools_build_gradle: String = "3.5.0"

  const val lint_gradle: String = "26.5.0"

  const val facebook_login: String = "4.42.0"

  const val com_github_bumptech_glide: String = "4.9.0"

  const val play_services_auth: String = "17.0.0"

  const val material: String = "1.1.0-alpha09"

  const val firebase_auth: String = "19.0.0"

  const val google_services: String = "4.3.2"

  const val truth: String = "1.0"

  const val com_gradle_build_scan_gradle_plugin: String = "2.4.1"

  const val com_jakewharton: String = "10.1.0"

  const val com_squareup_leakcanary: String = "1.6.3"

  const val com_squareup_retrofit2: String = "2.6.1"

  const val twitter_core: String = "3.3.0"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

  const val junit: String = "4.12"

  const val materialProgress: String = "1.6.1"

  const val org_gradle_kotlin_kotlin_dsl_gradle_plugin: String = "1.2.11"

  const val kotlin_gradle_plugin: String = "1.3.50"

  const val kotlin_reflect: String = "1.3.50"

  const val kotlin_sam_with_receiver: String = "1.3.50"

  const val kotlin_scripting_compiler_embeddable: String = "1.3.50"

  const val kotlin_stdlib_jdk8: String = "1.3.50"

  const val mockito_android: String = "2.21.0"

  const val robolectric: String = "4.3"

  const val easypermissions: String = "1.3.0"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.2"

  const val gradleCurrentVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
